# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/easy_webrtc_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/easy_webrtc_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/easy_webrtc_server/CMakeFiles /home/easy_webrtc_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/easy_webrtc_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named publish

# Build rule for target.
publish: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 publish
.PHONY : publish

# fast build rule for target.
publish/fast:
	$(MAKE) -f CMakeFiles/publish.dir/build.make CMakeFiles/publish.dir/build
.PHONY : publish/fast

#=============================================================================
# Target rules for targets named picAnalyse

# Build rule for target.
picAnalyse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picAnalyse
.PHONY : picAnalyse

# fast build rule for target.
picAnalyse/fast:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/build
.PHONY : picAnalyse/fast

#=============================================================================
# Target rules for targets named rtp_src_example_pinjie

# Build rule for target.
rtp_src_example_pinjie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtp_src_example_pinjie
.PHONY : rtp_src_example_pinjie

# fast build rule for target.
rtp_src_example_pinjie/fast:
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/build
.PHONY : rtp_src_example_pinjie/fast

#=============================================================================
# Target rules for targets named rtp_src_example

# Build rule for target.
rtp_src_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtp_src_example
.PHONY : rtp_src_example

# fast build rule for target.
rtp_src_example/fast:
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/build
.PHONY : rtp_src_example/fast

#=============================================================================
# Target rules for targets named rtc

# Build rule for target.
rtc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtc
.PHONY : rtc

# fast build rule for target.
rtc/fast:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/build
.PHONY : rtc/fast

common/crypto.o: common/crypto.cc.o

.PHONY : common/crypto.o

# target to build an object file
common/crypto.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/crypto.cc.o
.PHONY : common/crypto.cc.o

common/crypto.i: common/crypto.cc.i

.PHONY : common/crypto.i

# target to preprocess a source file
common/crypto.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/crypto.cc.i
.PHONY : common/crypto.cc.i

common/crypto.s: common/crypto.cc.s

.PHONY : common/crypto.s

# target to generate assembly for a file
common/crypto.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/crypto.cc.s
.PHONY : common/crypto.cc.s

common/file.o: common/file.cc.o

.PHONY : common/file.o

# target to build an object file
common/file.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/file.cc.o
.PHONY : common/file.cc.o

common/file.i: common/file.cc.i

.PHONY : common/file.i

# target to preprocess a source file
common/file.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/file.cc.i
.PHONY : common/file.cc.i

common/file.s: common/file.cc.s

.PHONY : common/file.s

# target to generate assembly for a file
common/file.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/file.cc.s
.PHONY : common/file.cc.s

common/ip.o: common/ip.cc.o

.PHONY : common/ip.o

# target to build an object file
common/ip.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/ip.cc.o
.PHONY : common/ip.cc.o

common/ip.i: common/ip.cc.i

.PHONY : common/ip.i

# target to preprocess a source file
common/ip.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/ip.cc.i
.PHONY : common/ip.cc.i

common/ip.s: common/ip.cc.s

.PHONY : common/ip.s

# target to generate assembly for a file
common/ip.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/ip.cc.s
.PHONY : common/ip.cc.s

common/logger.o: common/logger.cc.o

.PHONY : common/logger.o

# target to build an object file
common/logger.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/logger.cc.o
.PHONY : common/logger.cc.o

common/logger.i: common/logger.cc.i

.PHONY : common/logger.i

# target to preprocess a source file
common/logger.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/logger.cc.i
.PHONY : common/logger.cc.i

common/logger.s: common/logger.cc.s

.PHONY : common/logger.s

# target to generate assembly for a file
common/logger.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/logger.cc.s
.PHONY : common/logger.cc.s

common/settings.o: common/settings.cc.o

.PHONY : common/settings.o

# target to build an object file
common/settings.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/settings.cc.o
.PHONY : common/settings.cc.o

common/settings.i: common/settings.cc.i

.PHONY : common/settings.i

# target to preprocess a source file
common/settings.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/settings.cc.i
.PHONY : common/settings.cc.i

common/settings.s: common/settings.cc.s

.PHONY : common/settings.s

# target to generate assembly for a file
common/settings.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/common/settings.cc.s
.PHONY : common/settings.cc.s

example/publish.o: example/publish.cc.o

.PHONY : example/publish.o

# target to build an object file
example/publish.cc.o:
	$(MAKE) -f CMakeFiles/publish.dir/build.make CMakeFiles/publish.dir/example/publish.cc.o
.PHONY : example/publish.cc.o

example/publish.i: example/publish.cc.i

.PHONY : example/publish.i

# target to preprocess a source file
example/publish.cc.i:
	$(MAKE) -f CMakeFiles/publish.dir/build.make CMakeFiles/publish.dir/example/publish.cc.i
.PHONY : example/publish.cc.i

example/publish.s: example/publish.cc.s

.PHONY : example/publish.s

# target to generate assembly for a file
example/publish.cc.s:
	$(MAKE) -f CMakeFiles/publish.dir/build.make CMakeFiles/publish.dir/example/publish.cc.s
.PHONY : example/publish.cc.s

example/rtp_src_example-pinjie.o: example/rtp_src_example-pinjie.cc.o

.PHONY : example/rtp_src_example-pinjie.o

# target to build an object file
example/rtp_src_example-pinjie.cc.o:
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/example/rtp_src_example-pinjie.cc.o
.PHONY : example/rtp_src_example-pinjie.cc.o

example/rtp_src_example-pinjie.i: example/rtp_src_example-pinjie.cc.i

.PHONY : example/rtp_src_example-pinjie.i

# target to preprocess a source file
example/rtp_src_example-pinjie.cc.i:
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/example/rtp_src_example-pinjie.cc.i
.PHONY : example/rtp_src_example-pinjie.cc.i

example/rtp_src_example-pinjie.s: example/rtp_src_example-pinjie.cc.s

.PHONY : example/rtp_src_example-pinjie.s

# target to generate assembly for a file
example/rtp_src_example-pinjie.cc.s:
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/example/rtp_src_example-pinjie.cc.s
.PHONY : example/rtp_src_example-pinjie.cc.s

example/rtp_src_example.o: example/rtp_src_example.cc.o

.PHONY : example/rtp_src_example.o

# target to build an object file
example/rtp_src_example.cc.o:
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/example/rtp_src_example.cc.o
.PHONY : example/rtp_src_example.cc.o

example/rtp_src_example.i: example/rtp_src_example.cc.i

.PHONY : example/rtp_src_example.i

# target to preprocess a source file
example/rtp_src_example.cc.i:
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/example/rtp_src_example.cc.i
.PHONY : example/rtp_src_example.cc.i

example/rtp_src_example.s: example/rtp_src_example.cc.s

.PHONY : example/rtp_src_example.s

# target to generate assembly for a file
example/rtp_src_example.cc.s:
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/example/rtp_src_example.cc.s
.PHONY : example/rtp_src_example.cc.s

example/rtp_src_yc-picAnalyse.o: example/rtp_src_yc-picAnalyse.cc.o

.PHONY : example/rtp_src_yc-picAnalyse.o

# target to build an object file
example/rtp_src_yc-picAnalyse.cc.o:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/example/rtp_src_yc-picAnalyse.cc.o
.PHONY : example/rtp_src_yc-picAnalyse.cc.o

example/rtp_src_yc-picAnalyse.i: example/rtp_src_yc-picAnalyse.cc.i

.PHONY : example/rtp_src_yc-picAnalyse.i

# target to preprocess a source file
example/rtp_src_yc-picAnalyse.cc.i:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/example/rtp_src_yc-picAnalyse.cc.i
.PHONY : example/rtp_src_yc-picAnalyse.cc.i

example/rtp_src_yc-picAnalyse.s: example/rtp_src_yc-picAnalyse.cc.s

.PHONY : example/rtp_src_yc-picAnalyse.s

# target to generate assembly for a file
example/rtp_src_yc-picAnalyse.cc.s:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/example/rtp_src_yc-picAnalyse.cc.s
.PHONY : example/rtp_src_yc-picAnalyse.cc.s

include/ftplib.o: include/ftplib.cc.o

.PHONY : include/ftplib.o

# target to build an object file
include/ftplib.cc.o:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/include/ftplib.cc.o
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/include/ftplib.cc.o
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/include/ftplib.cc.o
.PHONY : include/ftplib.cc.o

include/ftplib.i: include/ftplib.cc.i

.PHONY : include/ftplib.i

# target to preprocess a source file
include/ftplib.cc.i:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/include/ftplib.cc.i
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/include/ftplib.cc.i
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/include/ftplib.cc.i
.PHONY : include/ftplib.cc.i

include/ftplib.s: include/ftplib.cc.s

.PHONY : include/ftplib.s

# target to generate assembly for a file
include/ftplib.cc.s:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/include/ftplib.cc.s
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/include/ftplib.cc.s
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/include/ftplib.cc.s
.PHONY : include/ftplib.cc.s

net/udp_connection.o: net/udp_connection.cc.o

.PHONY : net/udp_connection.o

# target to build an object file
net/udp_connection.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/net/udp_connection.cc.o
.PHONY : net/udp_connection.cc.o

net/udp_connection.i: net/udp_connection.cc.i

.PHONY : net/udp_connection.i

# target to preprocess a source file
net/udp_connection.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/net/udp_connection.cc.i
.PHONY : net/udp_connection.cc.i

net/udp_connection.s: net/udp_connection.cc.s

.PHONY : net/udp_connection.s

# target to generate assembly for a file
net/udp_connection.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/net/udp_connection.cc.s
.PHONY : net/udp_connection.cc.s

net/udp_server.o: net/udp_server.cc.o

.PHONY : net/udp_server.o

# target to build an object file
net/udp_server.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/net/udp_server.cc.o
.PHONY : net/udp_server.cc.o

net/udp_server.i: net/udp_server.cc.i

.PHONY : net/udp_server.i

# target to preprocess a source file
net/udp_server.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/net/udp_server.cc.i
.PHONY : net/udp_server.cc.i

net/udp_server.s: net/udp_server.cc.s

.PHONY : net/udp_server.s

# target to generate assembly for a file
net/udp_server.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/net/udp_server.cc.s
.PHONY : net/udp_server.cc.s

rtc/dtls_transport.o: rtc/dtls_transport.cc.o

.PHONY : rtc/dtls_transport.o

# target to build an object file
rtc/dtls_transport.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/dtls_transport.cc.o
.PHONY : rtc/dtls_transport.cc.o

rtc/dtls_transport.i: rtc/dtls_transport.cc.i

.PHONY : rtc/dtls_transport.i

# target to preprocess a source file
rtc/dtls_transport.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/dtls_transport.cc.i
.PHONY : rtc/dtls_transport.cc.i

rtc/dtls_transport.s: rtc/dtls_transport.cc.s

.PHONY : rtc/dtls_transport.s

# target to generate assembly for a file
rtc/dtls_transport.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/dtls_transport.cc.s
.PHONY : rtc/dtls_transport.cc.s

rtc/ice_server.o: rtc/ice_server.cc.o

.PHONY : rtc/ice_server.o

# target to build an object file
rtc/ice_server.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/ice_server.cc.o
.PHONY : rtc/ice_server.cc.o

rtc/ice_server.i: rtc/ice_server.cc.i

.PHONY : rtc/ice_server.i

# target to preprocess a source file
rtc/ice_server.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/ice_server.cc.i
.PHONY : rtc/ice_server.cc.i

rtc/ice_server.s: rtc/ice_server.cc.s

.PHONY : rtc/ice_server.s

# target to generate assembly for a file
rtc/ice_server.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/ice_server.cc.s
.PHONY : rtc/ice_server.cc.s

rtc/srtp_session.o: rtc/srtp_session.cc.o

.PHONY : rtc/srtp_session.o

# target to build an object file
rtc/srtp_session.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/srtp_session.cc.o
.PHONY : rtc/srtp_session.cc.o

rtc/srtp_session.i: rtc/srtp_session.cc.i

.PHONY : rtc/srtp_session.i

# target to preprocess a source file
rtc/srtp_session.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/srtp_session.cc.i
.PHONY : rtc/srtp_session.cc.i

rtc/srtp_session.s: rtc/srtp_session.cc.s

.PHONY : rtc/srtp_session.s

# target to generate assembly for a file
rtc/srtp_session.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/srtp_session.cc.s
.PHONY : rtc/srtp_session.cc.s

rtc/stun_packet.o: rtc/stun_packet.cc.o

.PHONY : rtc/stun_packet.o

# target to build an object file
rtc/stun_packet.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/stun_packet.cc.o
.PHONY : rtc/stun_packet.cc.o

rtc/stun_packet.i: rtc/stun_packet.cc.i

.PHONY : rtc/stun_packet.i

# target to preprocess a source file
rtc/stun_packet.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/stun_packet.cc.i
.PHONY : rtc/stun_packet.cc.i

rtc/stun_packet.s: rtc/stun_packet.cc.s

.PHONY : rtc/stun_packet.s

# target to generate assembly for a file
rtc/stun_packet.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/stun_packet.cc.s
.PHONY : rtc/stun_packet.cc.s

rtc/webrtc_transport.o: rtc/webrtc_transport.cc.o

.PHONY : rtc/webrtc_transport.o

# target to build an object file
rtc/webrtc_transport.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/webrtc_transport.cc.o
.PHONY : rtc/webrtc_transport.cc.o

rtc/webrtc_transport.i: rtc/webrtc_transport.cc.i

.PHONY : rtc/webrtc_transport.i

# target to preprocess a source file
rtc/webrtc_transport.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/webrtc_transport.cc.i
.PHONY : rtc/webrtc_transport.cc.i

rtc/webrtc_transport.s: rtc/webrtc_transport.cc.s

.PHONY : rtc/webrtc_transport.s

# target to generate assembly for a file
rtc/webrtc_transport.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtc/webrtc_transport.cc.s
.PHONY : rtc/webrtc_transport.cc.s

rtp/rtp_packet.o: rtp/rtp_packet.cc.o

.PHONY : rtp/rtp_packet.o

# target to build an object file
rtp/rtp_packet.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/rtp_packet.cc.o
.PHONY : rtp/rtp_packet.cc.o

rtp/rtp_packet.i: rtp/rtp_packet.cc.i

.PHONY : rtp/rtp_packet.i

# target to preprocess a source file
rtp/rtp_packet.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/rtp_packet.cc.i
.PHONY : rtp/rtp_packet.cc.i

rtp/rtp_packet.s: rtp/rtp_packet.cc.s

.PHONY : rtp/rtp_packet.s

# target to generate assembly for a file
rtp/rtp_packet.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/rtp_packet.cc.s
.PHONY : rtp/rtp_packet.cc.s

rtp/rtp_util.o: rtp/rtp_util.cc.o

.PHONY : rtp/rtp_util.o

# target to build an object file
rtp/rtp_util.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/rtp_util.cc.o
.PHONY : rtp/rtp_util.cc.o

rtp/rtp_util.i: rtp/rtp_util.cc.i

.PHONY : rtp/rtp_util.i

# target to preprocess a source file
rtp/rtp_util.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/rtp_util.cc.i
.PHONY : rtp/rtp_util.cc.i

rtp/rtp_util.s: rtp/rtp_util.cc.s

.PHONY : rtp/rtp_util.s

# target to generate assembly for a file
rtp/rtp_util.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/rtp_util.cc.s
.PHONY : rtp/rtp_util.cc.s

rtp/video_rtp_depacketizer.o: rtp/video_rtp_depacketizer.cc.o

.PHONY : rtp/video_rtp_depacketizer.o

# target to build an object file
rtp/video_rtp_depacketizer.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/video_rtp_depacketizer.cc.o
.PHONY : rtp/video_rtp_depacketizer.cc.o

rtp/video_rtp_depacketizer.i: rtp/video_rtp_depacketizer.cc.i

.PHONY : rtp/video_rtp_depacketizer.i

# target to preprocess a source file
rtp/video_rtp_depacketizer.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/video_rtp_depacketizer.cc.i
.PHONY : rtp/video_rtp_depacketizer.cc.i

rtp/video_rtp_depacketizer.s: rtp/video_rtp_depacketizer.cc.s

.PHONY : rtp/video_rtp_depacketizer.s

# target to generate assembly for a file
rtp/video_rtp_depacketizer.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/video_rtp_depacketizer.cc.s
.PHONY : rtp/video_rtp_depacketizer.cc.s

rtp/video_rtp_depacketizer_h264.o: rtp/video_rtp_depacketizer_h264.cc.o

.PHONY : rtp/video_rtp_depacketizer_h264.o

# target to build an object file
rtp/video_rtp_depacketizer_h264.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/video_rtp_depacketizer_h264.cc.o
.PHONY : rtp/video_rtp_depacketizer_h264.cc.o

rtp/video_rtp_depacketizer_h264.i: rtp/video_rtp_depacketizer_h264.cc.i

.PHONY : rtp/video_rtp_depacketizer_h264.i

# target to preprocess a source file
rtp/video_rtp_depacketizer_h264.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/video_rtp_depacketizer_h264.cc.i
.PHONY : rtp/video_rtp_depacketizer_h264.cc.i

rtp/video_rtp_depacketizer_h264.s: rtp/video_rtp_depacketizer_h264.cc.s

.PHONY : rtp/video_rtp_depacketizer_h264.s

# target to generate assembly for a file
rtp/video_rtp_depacketizer_h264.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/rtp/video_rtp_depacketizer_h264.cc.s
.PHONY : rtp/video_rtp_depacketizer_h264.cc.s

session/webrtc_session.o: session/webrtc_session.cc.o

.PHONY : session/webrtc_session.o

# target to build an object file
session/webrtc_session.cc.o:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/session/webrtc_session.cc.o
.PHONY : session/webrtc_session.cc.o

session/webrtc_session.i: session/webrtc_session.cc.i

.PHONY : session/webrtc_session.i

# target to preprocess a source file
session/webrtc_session.cc.i:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/session/webrtc_session.cc.i
.PHONY : session/webrtc_session.cc.i

session/webrtc_session.s: session/webrtc_session.cc.s

.PHONY : session/webrtc_session.s

# target to generate assembly for a file
session/webrtc_session.cc.s:
	$(MAKE) -f CMakeFiles/rtc.dir/build.make CMakeFiles/rtc.dir/session/webrtc_session.cc.s
.PHONY : session/webrtc_session.cc.s

sources/json_reader.o: sources/json_reader.cpp.o

.PHONY : sources/json_reader.o

# target to build an object file
sources/json_reader.cpp.o:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_reader.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_reader.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_reader.cpp.o
.PHONY : sources/json_reader.cpp.o

sources/json_reader.i: sources/json_reader.cpp.i

.PHONY : sources/json_reader.i

# target to preprocess a source file
sources/json_reader.cpp.i:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_reader.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_reader.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_reader.cpp.i
.PHONY : sources/json_reader.cpp.i

sources/json_reader.s: sources/json_reader.cpp.s

.PHONY : sources/json_reader.s

# target to generate assembly for a file
sources/json_reader.cpp.s:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_reader.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_reader.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_reader.cpp.s
.PHONY : sources/json_reader.cpp.s

sources/json_value.o: sources/json_value.cpp.o

.PHONY : sources/json_value.o

# target to build an object file
sources/json_value.cpp.o:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_value.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_value.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_value.cpp.o
.PHONY : sources/json_value.cpp.o

sources/json_value.i: sources/json_value.cpp.i

.PHONY : sources/json_value.i

# target to preprocess a source file
sources/json_value.cpp.i:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_value.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_value.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_value.cpp.i
.PHONY : sources/json_value.cpp.i

sources/json_value.s: sources/json_value.cpp.s

.PHONY : sources/json_value.s

# target to generate assembly for a file
sources/json_value.cpp.s:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_value.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_value.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_value.cpp.s
.PHONY : sources/json_value.cpp.s

sources/json_writer.o: sources/json_writer.cpp.o

.PHONY : sources/json_writer.o

# target to build an object file
sources/json_writer.cpp.o:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_writer.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_writer.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_writer.cpp.o
.PHONY : sources/json_writer.cpp.o

sources/json_writer.i: sources/json_writer.cpp.i

.PHONY : sources/json_writer.i

# target to preprocess a source file
sources/json_writer.cpp.i:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_writer.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_writer.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_writer.cpp.i
.PHONY : sources/json_writer.cpp.i

sources/json_writer.s: sources/json_writer.cpp.s

.PHONY : sources/json_writer.s

# target to generate assembly for a file
sources/json_writer.cpp.s:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/json_writer.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/json_writer.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/json_writer.cpp.s
.PHONY : sources/json_writer.cpp.s

sources/shm_buf.o: sources/shm_buf.cpp.o

.PHONY : sources/shm_buf.o

# target to build an object file
sources/shm_buf.cpp.o:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/shm_buf.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/shm_buf.cpp.o
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/shm_buf.cpp.o
.PHONY : sources/shm_buf.cpp.o

sources/shm_buf.i: sources/shm_buf.cpp.i

.PHONY : sources/shm_buf.i

# target to preprocess a source file
sources/shm_buf.cpp.i:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/shm_buf.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/shm_buf.cpp.i
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/shm_buf.cpp.i
.PHONY : sources/shm_buf.cpp.i

sources/shm_buf.s: sources/shm_buf.cpp.s

.PHONY : sources/shm_buf.s

# target to generate assembly for a file
sources/shm_buf.cpp.s:
	$(MAKE) -f CMakeFiles/picAnalyse.dir/build.make CMakeFiles/picAnalyse.dir/sources/shm_buf.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example_pinjie.dir/build.make CMakeFiles/rtp_src_example_pinjie.dir/sources/shm_buf.cpp.s
	$(MAKE) -f CMakeFiles/rtp_src_example.dir/build.make CMakeFiles/rtp_src_example.dir/sources/shm_buf.cpp.s
.PHONY : sources/shm_buf.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... publish"
	@echo "... picAnalyse"
	@echo "... rtp_src_example_pinjie"
	@echo "... rtp_src_example"
	@echo "... edit_cache"
	@echo "... rtc"
	@echo "... common/crypto.o"
	@echo "... common/crypto.i"
	@echo "... common/crypto.s"
	@echo "... common/file.o"
	@echo "... common/file.i"
	@echo "... common/file.s"
	@echo "... common/ip.o"
	@echo "... common/ip.i"
	@echo "... common/ip.s"
	@echo "... common/logger.o"
	@echo "... common/logger.i"
	@echo "... common/logger.s"
	@echo "... common/settings.o"
	@echo "... common/settings.i"
	@echo "... common/settings.s"
	@echo "... example/publish.o"
	@echo "... example/publish.i"
	@echo "... example/publish.s"
	@echo "... example/rtp_src_example-pinjie.o"
	@echo "... example/rtp_src_example-pinjie.i"
	@echo "... example/rtp_src_example-pinjie.s"
	@echo "... example/rtp_src_example.o"
	@echo "... example/rtp_src_example.i"
	@echo "... example/rtp_src_example.s"
	@echo "... example/rtp_src_yc-picAnalyse.o"
	@echo "... example/rtp_src_yc-picAnalyse.i"
	@echo "... example/rtp_src_yc-picAnalyse.s"
	@echo "... include/ftplib.o"
	@echo "... include/ftplib.i"
	@echo "... include/ftplib.s"
	@echo "... net/udp_connection.o"
	@echo "... net/udp_connection.i"
	@echo "... net/udp_connection.s"
	@echo "... net/udp_server.o"
	@echo "... net/udp_server.i"
	@echo "... net/udp_server.s"
	@echo "... rtc/dtls_transport.o"
	@echo "... rtc/dtls_transport.i"
	@echo "... rtc/dtls_transport.s"
	@echo "... rtc/ice_server.o"
	@echo "... rtc/ice_server.i"
	@echo "... rtc/ice_server.s"
	@echo "... rtc/srtp_session.o"
	@echo "... rtc/srtp_session.i"
	@echo "... rtc/srtp_session.s"
	@echo "... rtc/stun_packet.o"
	@echo "... rtc/stun_packet.i"
	@echo "... rtc/stun_packet.s"
	@echo "... rtc/webrtc_transport.o"
	@echo "... rtc/webrtc_transport.i"
	@echo "... rtc/webrtc_transport.s"
	@echo "... rtp/rtp_packet.o"
	@echo "... rtp/rtp_packet.i"
	@echo "... rtp/rtp_packet.s"
	@echo "... rtp/rtp_util.o"
	@echo "... rtp/rtp_util.i"
	@echo "... rtp/rtp_util.s"
	@echo "... rtp/video_rtp_depacketizer.o"
	@echo "... rtp/video_rtp_depacketizer.i"
	@echo "... rtp/video_rtp_depacketizer.s"
	@echo "... rtp/video_rtp_depacketizer_h264.o"
	@echo "... rtp/video_rtp_depacketizer_h264.i"
	@echo "... rtp/video_rtp_depacketizer_h264.s"
	@echo "... session/webrtc_session.o"
	@echo "... session/webrtc_session.i"
	@echo "... session/webrtc_session.s"
	@echo "... sources/json_reader.o"
	@echo "... sources/json_reader.i"
	@echo "... sources/json_reader.s"
	@echo "... sources/json_value.o"
	@echo "... sources/json_value.i"
	@echo "... sources/json_value.s"
	@echo "... sources/json_writer.o"
	@echo "... sources/json_writer.i"
	@echo "... sources/json_writer.s"
	@echo "... sources/shm_buf.o"
	@echo "... sources/shm_buf.i"
	@echo "... sources/shm_buf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

